all: 
	g++ -std=c++11 -I ~/include rmm_tree_classic_v2.cpp -o rmm_tree_classic_v2 /usr/local/lib/libsdsl.a
	g++ -std=c++11 -I ~/include rmm_tree_classic_v2.cpp -o rmm_tree_classic_v2 /usr/local/lib/libsdsl.a