all:
	g++ -std=c++11 -I ~/include -o rmm_tree_classic_v3 rmm_tree_classic_v3.cpp principal.cpp -Wall /usr/local/lib/libsdsl.a
	./rmm_tree_classic_v3
	
v2:
	g++ -std=c++11 -I ~/include rmm_tree_classic_v2.cpp -o rmm_tree_classic_v2 -Wall /usr/local/lib/libsdsl.a
	./rmm_tree_classic_v2